### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by Leeiio** [ramiel/mongoose-sequence#42] opened 2019-01-24 12:04 UTC
(node:84409) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.

My mongoose version is v5.4.6.

**Comment by ramiel** [comment] 2019-01-24 12:38
There is no `findAndModify` in this plugin. an it be a query of yours?

**Comment by Leeiio** [comment] 2019-01-24 13:15
It's weird :( 
It's my model file:
```
const mongoose  = require('mongoose');
const Schema    = mongoose.Schema;
const AutoIncrement = require('mongoose-sequence')(mongoose);

var NotifyRecord = new Schema({
  time: { type: String }
}, { 
  timestamps: {
    createdAt: 'created_at',
    updatedAt: 'updated_at'
  }
});

NotifyRecord.plugin(AutoIncrement, {inc_field: 'notifyrec_id'});
NotifyRecord.index({time: 1});

mongoose.model('NotifyRecord', NotifyRecord);
```
When i use create() to create things, it shows `(node:84409) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.` in my terminal. But after i remove the plugin `AutoIncrement`, nothing warned in my terminal.

**Comment by ramiel** [comment] 2019-01-24 15:15
I think I found [the cause](https://github.com/ramiel/mongoose-sequence/blob/master/lib/sequence.js#L243). I'll push a fix soon

**Comment by ramiel** [comment] 2019-02-12 09:15
This has been fixed in version 5. Also, you should put `mongoose.set('useFindAndModify', false)` in your code, as explained at https://github.com/Automattic/mongoose/issues/7108#issuecomment-427881150

**Closed by ramiel** 2019-02-12 09:15 UTC

**Comment by dandv** [comment] 2020-04-15 02:08
Thanks for the solution to run `mongoose.set('useFindAndModify', false)`. It also fixed this warning I was getting:

> DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated
