### ISSUE TITLE
Adding a sequence to a schema never resolves when using save()

### ISSUE THREAD

**Issue by xorbis** [ramiel/mongoose-sequence#20] opened 2017-08-01 18:31 UTC
Without the plugin installed and configured on a schema, I can POST to my Rest API and receive a response.

With this installation, requests timeout (custom timer of 3 seconds) with no error throw while inserting a new document with model.save().
```
var mongooseSequence = require("mongoose-sequence");

schema.plugin(mongooseSequence, {
  id: "invoice_no",
  inc_field: "no",
  collection_name: "sequence"
});
```
Using the following related npms:
"mongodb": "^2.2.30",
"mongoose": "^4.11.5",
"mongoose-delete": "^0.4.0",
"mongoose-sequence": "^3.2.0",

Please note mongoose-delete is another plugin and works fine.
Also note that the sequence collection is never created (same for counters collection when option is not specified).

**Comment by ramiel** [comment] 2017-08-01 19:11
I think this is the second issue I receive of someone which cannot save using this plugin. I need to investigate more. Meanwhile can you please post a more complete code, including the schema, the plugin and the model creation. Or better a link to the code if it is public.
Thanks

**Comment by xorbis** [comment] 2017-08-01 20:09
Unfortunately it's not public but I can give you these:
# cat schemas/invoice.js
```
var mongoose = require("mongoose");
var Schema = mongoose.Schema;
var ObjectId = Schema.Types.ObjectId;

module.exports = new Schema({
        _owner: ObjectId,
        subscription: ObjectId,
        order: String,
        due: Date,
        recurring: Boolean,
        gst: Number,
        qst: Number,
        amount: Number,
        paid: Boolean,
        convertible: Boolean,
        items: [{
                name: String,
                price: Number,
                quantity: Number,
                discount: Boolean
        }]
}, {
        collection: "invoice",
        sequence: "no"
});
```
The sequence option is read and fed to your plugin's inc_field option.
And here load our schemas:
```
    /**
     * Add a mongo schema
     * @param {string} name - Name of the schema
     * @param {object} schema - Schema object
     */
    addSchema(name, schema) {
        // Add mongoose-delete plugin
        if (schema.plugin) {
            schema.plugin(mongooseDelete, {
                deletedAt: true,
                deletedBy: true,
                overrideMethods: true,
                indexFields: true
            });

            let seq = schema.get("sequence");

            if (seq) {
                this.app.log("Schema " + name + " with sequence " + seq, this.app.LogLevels.DEBUG);
                schema.plugin(mongooseSequence, {
                    id: name + "_" + seq,
                    inc_field: seq,
                    collection_name: "sequence"
                });
            }
        } else this.app.log("Required file is not a schema for collection named: " + name, this.app.LogLevels.ERROR);

        // Add schema to internal list
        this.schemas[name] = this.mongoose.model(name, schema);
        this.schemas[name].userOwned = schema.get("userOwned");
        this.app.log("Added schema " + name, this.app.LogLevels.VERBOSE);
    }
```
And here we save a document:
```
    /**
     * Add a document to the current model
     * @param {object} req - Request object
     * @param {object} values - List of document values
     * @return {object} - Promise
     */
    addDocument(req, values) {
        if (!this.model) return Promise.reject("No model defined");

        return new Promise((resolve, reject) => {
            let model = this.app.mongoGetModel(this.model);
            let doc = new model(values);

            this.app.log("Saving document...", this.app.LogLevels.DEBUG);
            doc.save((err, savedDoc) => {
                this.app.log("This line is never reached when using mongoose-sequence", this.app.LogLevels.DEBUG);
                if (err) reject(err);
                else if (savedDoc) {
                    Controller.stat(req, this.model + ".post");
                    resolve(savedDoc);
                } else reject("Could not add document");
            });
        });
    }
    /**
     * Add a document to the current model
     * @param {object} req - Request object
     * @param {object} values - List of document values
     * @return {object} - Promise
     */
    addDocument(req, values) {
        if (!this.model) return Promise.reject("No model defined");

        return new Promise((resolve, reject) => {
            let model = this.app.mongoGetModel(this.model);
            let doc = new model(values);

            doc.save((err, savedDoc) => {
                if (err) reject(err);
                else if (savedDoc) {
                    Controller.stat(req, this.model + ".post");
                    resolve(savedDoc);
                } else reject("Could not add document");
            });
        });
    }
```

**Comment by ramiel** [comment] 2017-08-01 21:31
Ok perfect, I'll try during the next days. So if this
```js
if (seq) 
```
is false, the save goes well, isn't it?

**Comment by xorbis** [comment] 2017-08-01 22:47
Yeah.

**Comment by ramiel** [comment] 2017-08-02 08:25
I replicated your job on [https://github.com/ramiel/invoice-test](https://github.com/ramiel/invoice-test) and it seems to work. Can you have a look to see if you understand why there is this difference?

**Comment by ramiel** [comment] 2017-08-02 08:25
Or tell me if maybe this doesn't work for you

**Comment by xorbis** [comment] 2017-08-02 11:47
I see two differences I haven't mentionned, we use Bluebird promises and we are not using Mongoose promises, however wierd that is, it is the current project status. We are also warned with a deprecated Mongoose connection like so:

`(node:27846) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client`
AND

`(node:27846) DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead`

Bluebird promises like this:
`global.Promise = require("bluebird");`

Maybe this will help reproduce the problem.

**Comment by ramiel** [comment] 2017-08-02 11:48
I'll try soon

**Comment by ramiel** [comment] 2017-08-02 11:49
I get rid of the deprecation adding `useMongoDriver` to the options on the connection. By the way the code was working also in that case

**Comment by ramiel** [comment] 2017-08-02 16:24
I set up the project to use bluebird and nothing has changed (you can look at the repo). I'll investigate more but tell me if you spot some other difference. Another question: is my repo working on your machine?

**Comment by xorbis** [comment] 2017-08-02 19:53
Yes it works on thee same server and node environment than my Rest API, so the problem is not Bluebird.
I might have to node debug the call to save() in order to see where it hangs.

**Comment by xorbis** [comment] 2017-08-03 14:50
I am investigating this but all seems ok as per this issue:
[Stackoverflow](https://stackoverflow.com/questions/10156623/mongoose-js-instance-save-callback-not-firing)

**Comment by xorbis** [comment] 2017-08-03 14:54
Updating npm from 3.10.10 to 5.3.0 and running ncu -a on everything.

**Comment by xorbis** [comment] 2017-08-03 15:10
Node version is v6.11.1, all packages updated to latest version.
Same problem.

**Comment by ramiel** [comment] 2017-08-03 15:12
Yep, your issue is not related to the one on stackoverflow because without my plugin `save` works. I'll tell you more on the next days.

**Comment by xorbis** [comment] 2017-08-03 15:48
If it can help, this similar plugin works fine:
[mongodb-autoincrement](https://www.npmjs.com/package/mongodb-autoincrement)

**Comment by ramiel** [comment] 2017-08-04 07:13
This is a duplicate of #19 . Even in that case the problem was not replicable... :thinking:

**Comment by ramiel** [comment] 2017-08-04 07:20
I've got an idea. This plugin internally create a collection to handle the counters. In order to do it, it requires mongoose and create a schema and a model. If for some reason the mongoose my library is using, it's not the same your application is using to connect to mongo, the save will hang forever because the connection is never instantiated.
I'm going to see if I can change this, meanwhile can you do this test for me please? Remove your node_modules folder and install them again with `npm i --production`. Then launch the application and tell me if you receive an error saying that mongoose cannot be found as module

**Comment by ramiel** [comment] 2017-08-04 08:07
I think I solved the problem. While I'm doing the release please can you try to use this on your package.json and tell if it works?

```json
"dependencies":{
  "mongoose-sequence": "ramiel/mongoose-sequence#feature/shared_mongoose"
}
```

**Comment by xorbis** [comment] 2017-08-04 12:18
I might be able to test this next week, good news!

**Closed** 2017-08-05 11:54 UTC

**Comment by ramiel** [comment] 2017-08-05 12:00
Ok, simply update to version 4.0.0. I deprecated older version because of this bug.
